title: "The Intelligent Digital Twin Toolkit: Harnessing the Power of Artificial Intelligence to Accelerate Hardware Agility"
author: "L. Todd Kromann, Ph.D."
date: "2023-05-04"
output:
  pdf_document: default
  html_document: default
  word_document: default